// Mock data for BuxHat platform
export const artists = [
  {
    id: "1",
    name: "Wizkid",
    image: "/Wizkid.jpeg",
    followers: 12500000,
    genre: ["Afrobeats", "Hip-hop"],
    country: "Nigeria",
    trending: true,
    trendingRank: 1,
    trendChange: 12,
    breakoutPotential: 92,
    monthlyStreams: 15200000,
  },
  {
    id: "2",
    name: "Burna Boy",
    image: "/burna.png",
    followers: 11800000,
    genre: ["Afrobeats", "Reggae"],
    country: "Nigeria",
    trending: true,
    trendingRank: 2,
    trendChange: 8,
    breakoutPotential: 88,
    monthlyStreams: 14900000,
  },
  {
    id: "3",
    name: "Fola",
    image: "/fola.jpeg",
    followers: 5200000,
    genre: ["Afrobeats", "R&B"],
    country: "Nigeria",
    trending: true,
    trendingRank: 3,
    trendChange: 24,
    breakoutPotential: 85,
    monthlyStreams: 8700000,
  },
  {
    id: "4",
    name: "Tems",
    image: "/TEMS.jpeg",
    followers: 8900000,
    genre: ["Afrobeats", "Pop"],
    country: "Nigeria",
    trending: true,
    trendingRank: 4,
    trendChange: 5,
    breakoutPotential: 78,
    monthlyStreams: 7600000,
  },
  {
    id: "5",
    name: "Davido",
    image: "/davido.png",
    followers: 13200000,
    genre: ["Afrobeats", "Dance"],
    country: "Nigeria",
    trending: true,
    trendingRank: 5,
    trendChange: 8,
    breakoutPotential: 82,
    monthlyStreams: 12100000,
  },
  {
    id: "6",
    name: "Mavo",
    image: "/mavo.jpeg",
    followers: 4500000,
    genre: ["Afrobeats"],
    country: "Nigeria",
    trending: true,
    trendingRank: 6,
    trendChange: 31,
    breakoutPotential: 95,
    monthlyStreams: 9200000,
  },
  {
    id: "7",
    name: "Rema",
    image: "/rema.png",
    followers: 6800000,
    genre: ["Afrobeats"],
    country: "Nigeria",
    trending: true,
    trendingRank: 7,
    trendChange: 18,
    breakoutPotential: 89,
    monthlyStreams: 11300000,
  },
  {
    id: "8",
    name: "Asake",
    image: "/asake.jpeg",
    followers: 5600000,
    genre: ["Afrobeats", "Soul"],
    country: "Nigeria",
    trending: true,
    trendingRank: 8,
    trendChange: 9,
    breakoutPotential: 80,
    monthlyStreams: 8950000,
  },
];

export const trendData = [
  { month: "Jan", streams: 4000, engagement: 2400, sentiment: 65 },
  { month: "Feb", streams: 3200, engagement: 1398, sentiment: 68 },
  { month: "Mar", streams: 2800, engagement: 9800, sentiment: 72 },
  { month: "Apr", streams: 2780, engagement: 3908, sentiment: 75 },
  { month: "May", streams: 1890, engagement: 4800, sentiment: 78 },
  { month: "Jun", streams: 2390, engagement: 3800, sentiment: 82 },
  { month: "Jul", streams: 3490, engagement: 4300, sentiment: 85 },
  { month: "Aug", streams: 4200, engagement: 5200, sentiment: 88 },
  { month: "Sep", streams: 5100, engagement: 6100, sentiment: 90 },
  { month: "Oct", streams: 6200, engagement: 7300, sentiment: 92 },
  { month: "Nov", streams: 7300, engagement: 8100, sentiment: 94 },
  { month: "Dec", streams: 8500, engagement: 9200, sentiment: 96 },
];

export const breakoutArtists = [
  { name: "Amapiano Collective", potential: 95, momentum: 92, engagement: 88, x: 85, y: 90 },
  { name: "Rema", potential: 89, momentum: 78, engagement: 82, x: 82, y: 80 },
  { name: "CKay", potential: 85, momentum: 88, engagement: 85, x: 88, y: 86 },
  { name: "Fireboy DML", potential: 80, momentum: 72, engagement: 78, x: 75, y: 76 },
  { name: "Tiwa Savage", potential: 78, momentum: 65, engagement: 72, x: 68, y: 70 },
  { name: "Wizkid", potential: 92, momentum: 85, engagement: 95, x: 90, y: 92 },
  { name: "Burna Boy", potential: 88, momentum: 80, engagement: 92, x: 86, y: 88 },
  { name: "Davido", potential: 82, momentum: 70, engagement: 88, x: 75, y: 82 },
];

export const trendingNow = [
  {
    id: "1",
    artist: "Wizkid",
    song: "Essence",
    genre: "Afrobeats",
    streams: 2500000,
    change: 45,
    sentiment: 96,
  },
  {
    id: "2",
    artist: "Burna Boy",
    song: "Last Last",
    genre: "Afrobeats",
    streams: 2100000,
    change: 32,
    sentiment: 94,
  },
  {
    id: "3",
    artist: "CKay",
    song: "Love Nwantiti",
    genre: "Afrobeats",
    streams: 1950000,
    change: 58,
    sentiment: 92,
  },
  {
    id: "4",
    artist: "Amapiano Collective",
    song: "Piano Wave",
    genre: "Amapiano",
    streams: 1850000,
    change: 72,
    sentiment: 91,
  },
];

export const albums = [
  {
    id: 'al-1',
    title: 'Made in Lagos',
    artistId: '1',
    artist: 'Wizkid',
    cover: '/Wizkid.jpeg',
    genre: 'Afrobeats',
    change: 18,
  },
  {
    id: 'al-2',
    title: 'Love, Damini',
    artistId: '2',
    artist: 'Burna Boy',
    cover: '/burna.png',
    genre: 'Afrobeats',
    change: 12,
  },
  {
    id: 'al-3',
    title: 'Rave & Roses',
    artistId: '7',
    artist: 'Rema',
    cover: '/rema.png',
    genre: 'Afrobeats',
    change: 21,
  },
  {
    id: 'al-4',
    title: 'Timeless',
    artistId: '5',
    artist: 'Davido',
    cover: '/davido.png',
    genre: 'Afrobeats',
    change: 9,
  },
]

export const favorites = [
  {
    id: "1",
    name: "Wizkid",
    followers: 12500000,
    genre: "Afrobeats",
    monthlyStreams: 15200000,
  },
  {
    id: "3",
    name: "CKay",
    followers: 5200000,
    genre: "Afrobeats",
    monthlyStreams: 8700000,
  },
  {
    id: "6",
    name: "Amapiano Collective",
    followers: 4500000,
    genre: "Amapiano",
    monthlyStreams: 9200000,
  },
];

export const artistDetail = {
  id: "1",
  name: "Wizkid",
  image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=600&fit=crop",
  banner: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&h=400&fit=crop",
  bio: "Nigerian Afrobeats superstar with global influence",
  followers: 12500000,
  verified: true,
  genres: ["Afrobeats", "Hip-hop", "Pop"],
  monthlyStreams: 15200000,
  totalSongs: 247,
  collaborations: 89,
  topSongs: [
    { title: "Essence", streams: 2500000, featuring: "Tems" },
    { title: "Hoodlum", streams: 2100000, featuring: "Skepta" },
    { title: "Ojuelegba", streams: 1950000, featuring: "Drake" },
  ],
  socialSentiment: 92,
  trendMomentum: 85,
  breakoutPotential: 92,
};

export const chartDataComparison = [
  {
    month: "Jan",
    "Wizkid": 4000,
    "Burna Boy": 2400,
    "CKay": 2400,
    "Davido": 3200,
  },
  {
    month: "Feb",
    "Wizkid": 3000,
    "Burna Boy": 1398,
    "CKay": 2210,
    "Davido": 2900,
  },
  {
    month: "Mar",
    "Wizkid": 2000,
    "Burna Boy": 9800,
    "CKay": 2290,
    "Davido": 2000,
  },
  {
    month: "Apr",
    "Wizkid": 2780,
    "Burna Boy": 3908,
    "CKay": 2000,
    "Davido": 2181,
  },
  {
    month: "May",
    "Wizkid": 1890,
    "Burna Boy": 4800,
    "CKay": 2181,
    "Davido": 1500,
  },
  {
    month: "Jun",
    "Wizkid": 2390,
    "Burna Boy": 3800,
    "CKay": 2500,
    "Davido": 2100,
  },
];

// Scout analytics mock data
export const scoutTrendCharts = [
  { month: 'Jan', mentionsGrowth: 22, sentimentMomentum: 45, tiktokUsage: 18, anomalySpikes: 2, forecastGrowth: 28 },
  { month: 'Feb', mentionsGrowth: 18, sentimentMomentum: 52, tiktokUsage: 21, anomalySpikes: 1, forecastGrowth: 30 },
  { month: 'Mar', mentionsGrowth: 26, sentimentMomentum: 58, tiktokUsage: 35, anomalySpikes: 4, forecastGrowth: 34 },
  { month: 'Apr', mentionsGrowth: 34, sentimentMomentum: 61, tiktokUsage: 42, anomalySpikes: 6, forecastGrowth: 39 },
  { month: 'May', mentionsGrowth: 29, sentimentMomentum: 57, tiktokUsage: 38, anomalySpikes: 3, forecastGrowth: 36 },
  { month: 'Jun', mentionsGrowth: 41, sentimentMomentum: 66, tiktokUsage: 55, anomalySpikes: 8, forecastGrowth: 44 },
  { month: 'Jul', mentionsGrowth: 48, sentimentMomentum: 70, tiktokUsage: 62, anomalySpikes: 5, forecastGrowth: 51 },
  { month: 'Aug', mentionsGrowth: 44, sentimentMomentum: 68, tiktokUsage: 60, anomalySpikes: 4, forecastGrowth: 49 },
  { month: 'Sep', mentionsGrowth: 52, sentimentMomentum: 73, tiktokUsage: 74, anomalySpikes: 9, forecastGrowth: 57 },
  { month: 'Oct', mentionsGrowth: 57, sentimentMomentum: 76, tiktokUsage: 79, anomalySpikes: 6, forecastGrowth: 61 },
  { month: 'Nov', mentionsGrowth: 61, sentimentMomentum: 79, tiktokUsage: 83, anomalySpikes: 7, forecastGrowth: 66 },
  { month: 'Dec', mentionsGrowth: 68, sentimentMomentum: 82, tiktokUsage: 91, anomalySpikes: 10, forecastGrowth: 72 },
]

export const breakoutRadarRows = [
  {
    artistId: '6',
    tiktokUsageGrowth: 72,
    shazamSpikeLevel: 64,
    mentionsVelocity: 78,
    playlistGrowth: 59,
    breakoutProbability: 93,
  },
  {
    artistId: '7',
    tiktokUsageGrowth: 55,
    shazamSpikeLevel: 41,
    mentionsVelocity: 63,
    playlistGrowth: 52,
    breakoutProbability: 88,
  },
  {
    artistId: '3',
    tiktokUsageGrowth: 49,
    shazamSpikeLevel: 38,
    mentionsVelocity: 57,
    playlistGrowth: 46,
    breakoutProbability: 82,
  },
  {
    artistId: '8',
    tiktokUsageGrowth: 43,
    shazamSpikeLevel: 29,
    mentionsVelocity: 51,
    playlistGrowth: 44,
    breakoutProbability: 79,
  },
  {
    artistId: '1',
    tiktokUsageGrowth: 33,
    shazamSpikeLevel: 24,
    mentionsVelocity: 46,
    playlistGrowth: 31,
    breakoutProbability: 74,
  },
  {
    artistId: '2',
    tiktokUsageGrowth: 31,
    shazamSpikeLevel: 22,
    mentionsVelocity: 44,
    playlistGrowth: 29,
    breakoutProbability: 72,
  },
]

export const artistAnalyticsById: Record<
  string,
  {
    trendScore: number
    breakoutProbability: number
    mentionsVelocity: number
    sentimentMomentum: number
    tiktokUsageGrowth: number
    playlistGrowth: number
    forecastGrowth: number
    signalBreakdown: Array<{ label: string; value: number; hint: string }>
    forecastChart: Array<{ month: string; actual: number; forecast: number }>
  }
> = {
  '1': {
    trendScore: 91,
    breakoutProbability: 74,
    mentionsVelocity: 46,
    sentimentMomentum: 72,
    tiktokUsageGrowth: 33,
    playlistGrowth: 31,
    forecastGrowth: 42,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 46, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 72, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 33, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 31, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 24, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 41, forecast: 43 },
      { month: 'Oct', actual: 45, forecast: 47 },
      { month: 'Nov', actual: 48, forecast: 52 },
      { month: 'Dec', actual: 54, forecast: 58 },
    ],
  },
  '2': {
    trendScore: 89,
    breakoutProbability: 72,
    mentionsVelocity: 44,
    sentimentMomentum: 69,
    tiktokUsageGrowth: 31,
    playlistGrowth: 29,
    forecastGrowth: 40,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 44, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 69, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 31, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 29, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 22, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 38, forecast: 40 },
      { month: 'Oct', actual: 41, forecast: 44 },
      { month: 'Nov', actual: 45, forecast: 49 },
      { month: 'Dec', actual: 50, forecast: 55 },
    ],
  },
  '3': {
    trendScore: 86,
    breakoutProbability: 82,
    mentionsVelocity: 57,
    sentimentMomentum: 63,
    tiktokUsageGrowth: 49,
    playlistGrowth: 46,
    forecastGrowth: 54,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 57, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 63, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 49, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 46, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 38, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 44, forecast: 47 },
      { month: 'Oct', actual: 49, forecast: 53 },
      { month: 'Nov', actual: 55, forecast: 60 },
      { month: 'Dec', actual: 63, forecast: 69 },
    ],
  },
  '4': {
    trendScore: 88,
    breakoutProbability: 77,
    mentionsVelocity: 49,
    sentimentMomentum: 75,
    tiktokUsageGrowth: 36,
    playlistGrowth: 34,
    forecastGrowth: 46,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 49, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 75, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 36, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 34, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 28, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 40, forecast: 42 },
      { month: 'Oct', actual: 44, forecast: 47 },
      { month: 'Nov', actual: 48, forecast: 52 },
      { month: 'Dec', actual: 55, forecast: 60 },
    ],
  },
  '5': {
    trendScore: 92,
    breakoutProbability: 81,
    mentionsVelocity: 54,
    sentimentMomentum: 70,
    tiktokUsageGrowth: 45,
    playlistGrowth: 41,
    forecastGrowth: 55,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 54, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 70, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 45, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 41, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 33, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 46, forecast: 49 },
      { month: 'Oct', actual: 52, forecast: 56 },
      { month: 'Nov', actual: 59, forecast: 64 },
      { month: 'Dec', actual: 67, forecast: 73 },
    ],
  },
  '6': {
    trendScore: 94,
    breakoutProbability: 93,
    mentionsVelocity: 78,
    sentimentMomentum: 74,
    tiktokUsageGrowth: 72,
    playlistGrowth: 59,
    forecastGrowth: 68,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 78, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 74, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 72, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 59, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 64, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 52, forecast: 56 },
      { month: 'Oct', actual: 59, forecast: 64 },
      { month: 'Nov', actual: 67, forecast: 73 },
      { month: 'Dec', actual: 76, forecast: 83 },
    ],
  },
  '7': {
    trendScore: 90,
    breakoutProbability: 88,
    mentionsVelocity: 63,
    sentimentMomentum: 71,
    tiktokUsageGrowth: 55,
    playlistGrowth: 52,
    forecastGrowth: 60,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 63, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 71, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 55, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 52, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 41, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 48, forecast: 51 },
      { month: 'Oct', actual: 54, forecast: 58 },
      { month: 'Nov', actual: 61, forecast: 66 },
      { month: 'Dec', actual: 69, forecast: 75 },
    ],
  },
  '8': {
    trendScore: 85,
    breakoutProbability: 79,
    mentionsVelocity: 51,
    sentimentMomentum: 62,
    tiktokUsageGrowth: 43,
    playlistGrowth: 44,
    forecastGrowth: 50,
    signalBreakdown: [
      { label: 'Mentions velocity', value: 51, hint: 'Daily mentions acceleration' },
      { label: 'Sentiment momentum', value: 62, hint: 'Positive/negative swing rate' },
      { label: 'TikTok audio usage', value: 43, hint: 'Audio reuse growth' },
      { label: 'Playlist growth', value: 44, hint: 'Net playlist adds' },
      { label: 'Shazam spike', value: 29, hint: 'Recognition lift' },
    ],
    forecastChart: [
      { month: 'Sep', actual: 43, forecast: 46 },
      { month: 'Oct', actual: 48, forecast: 52 },
      { month: 'Nov', actual: 54, forecast: 59 },
      { month: 'Dec', actual: 62, forecast: 68 },
    ],
  },
}
